version: "3.8"

services:
  traefik:
    image: traefik:v3.0
    env_file:
      - .env
    networks:
      - pterodactyl
    restart: always
    ports:
      - "8081:80" # We're actually running behind NGINX on the host instead of Traefik. I am not a fan of Traefik.
      - "8444:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_DIR}/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ${DATA_DIR}/traefik/acme.json:/acme.json

networks:
  pterodactyl:
    external: true
